# Python 3.11 AWS ECR Imaeg
FROM public.ecr.aws/lambda/python:3.11

# Installs Git and Updates the base image
RUN yum update -y
RUN yum install git -y

# Configuring workspace and installing python dependencies
WORKDIR /var/task
COPY ./src/subscriber .
COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["handler.main"]
