from .client.youtube_client import YoutubeClient


def main(event, _):
    action_name = event["actionName"]
    video_name = event["videoName"]

    if action_name == "getVideoId":
        response = action_get_video_id(video_name)

    return response


def action_get_video_id(video_name):
    youtube_client = YoutubeClient()
    video_id = youtube_client.get_video_id(video_name)
    return video_id


def action_get_transcript():
    pass


def action_get_autogenerated_blogpost():
    pass


def action_create_and_check_in_draft():
    pass
