name: "Black (FMT) Check - Python"

on:
  workflow_call:

jobs:
  format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5 # This action sets up Python

      - name: Install Dependencies
        run: pip install black # Install your Python dependencies

      - name: Format Check
        run: black --check lambdas/
